### ISSUE TITLE
lft and rgt values not reseted?

### ISSUE THREAD

**Issue by mathieuseguin** [skyeagle/nested_set#10]
irb(main):019:0> Category.create(:name => "test_1")
=> # Category id: 9, name: "test_1", parent_id: nil, lft: 1, rgt: 2, created_at: "2011-01-03 01:13:37", updated_at: "2011-01-03 01:13:37">
irb(main):020:0> Category.create(:name => "test_2")
=> # Category id: 10, name: "test_2", parent_id: nil, lft: 3, rgt: 4, created_at: "2011-01-03 01:13:39", updated_at: "2011-01-03 01:13:39">

Should not the lft and rgt values be reseted since they are both root categories?

**Comment by skyeagle** [comment]
What difference should be to select children from the first and the second roots in that case?

**Comment by skyeagle** [comment]
If you need independ roots you can try add scope:

```
acts_as_nested_set :scope => :user
```

In that case you will have scoped roots by user_id column.

**Comment by mathieuseguin** [comment]
The difference would be to have several unrelated trees saved in the same table.

I will try scope.

Thank you for your help
