### ISSUE TITLE
undefined method 'arrange'

### ISSUE THREAD

**Issue by anengineerdude** [skyeagle/nested_set#12]
Not sure if I am doing something wrong, or this is a bug, but I am getting an undefined method when trying to call 'arrange' on my model.

I am trying to call > Department.arrange on my model in https://github.com/ryanjmclaughlin/TrainingTracker/

Thanks.

**Comment by skyeagle** [comment]
Did you try to restart server or rails console? If it didn't help you could try to specify gem version in Gemfile to the latest one(1.6.3). I hope this help you.

**Comment by anengineerdude** [comment]
Looks to be working now.  I could have sworn I restarted the console!  Maybe it was just the lack of sleep.

Thanks!

**Comment by anengineerdude** [comment]
all set
