### ISSUE TITLE
TypeError: nil can't be coerced into Fixnum - on setting a parent

### ISSUE THREAD

**Issue by bitcoiners** [skyeagle/nested_set#14]
<p> Using Rails 3 and ruby 1.9.2 and the latest version of nested_set 1.6.3
I am am having problems creating a model that acts_as_nested_set with parent id.</p>

<p>If I set parent id as nil, the model gets created, but if I set it anything else I get this error: </p>

<code>
ruby-1.9.2-p136 :007 > Mark.create({:markable_id=>1, :markable_type=>"Video", :context_user_id=>1, :user_id=>1, :type=>"Mark", :context_id=>2, :title=>"label", <strong>:parent_id=> nil</strong>})
# Mark:0xc543934 {

```
             :id => 26,
           :type => "Mark",
  :markable_type => "Video",
        :user_id => 1,
:context_user_id => 1,
     :context_id => 2,
    :markable_id => 1,
      :parent_id => nil,
            :lft => 51,
            :rgt => 52,
          :depth => nil,
           :html => nil,
          :title => "label",
           :body => "",
     :created_at => Wed, 26 Jan 2011 05:36:11 UTC +00:00,
     :updated_at => Wed, 26 Jan 2011 05:36:11 UTC +00:00
```

}
ruby-1.9.2-p136 :007 >   mark = Mark.create({:markable_id=>1, :markable_type=>"Video", :context_user_id=>1, :user_id=>1, :type=>"Mark", :context_id=>2, :title=>"label", <strong>:parent_id=> 26</strong>})

<blockquote>
  Context Load (0.2ms)  SELECT "contexts".* FROM "contexts" WHERE "contexts"."id" = 2 LIMIT 1
  ContextUser Load (0.1ms)  SELECT "context_users".* FROM "context_users" WHERE "context_users"."id" = 1 LIMIT 1
  SQL (0.1ms)  SELECT MAX("marks"."rgt") AS max_id FROM "marks" WHERE "marks"."markable_id" = 1 AND "marks"."markable_type" = 'Video'
  AREL (0.3ms)  INSERT INTO "marks" ("type", "markable_type", "user_id", "context_user_id", "context_id", "markable_id", "parent_id", "lft", "rgt", "depth", "html", "title", "body", "created_at", "updated_at") VALUES ('Mark', 'Video', 1, 1, 2, 1, 26, 53, 54, NULL, NULL, 'label', '', '2011-01-26 05:36:32.956603', '2011-01-26 05:36:32.956603')
  Mark Load (0.5ms)  SELECT "marks".* FROM "marks" WHERE "marks"."markable_id" = 1 AND "marks"."markable_type" = 'Video' AND "marks"."id" = 26 ORDER BY "marks"."lft" LIMIT 1
  Mark Load (0.1ms)  SELECT "lft", "rgt", "parent_id" FROM "marks" WHERE "marks"."id" = 27 LIMIT 1
  AREL (0.5ms)  UPDATE "marks" SET "lft" = CASE WHEN "lft" BETWEEN 52 AND 52 THEN "lft" + 54 - 52 WHEN "lft" BETWEEN 53 AND 54 THEN "lft" + 52 - 53 ELSE "lft" END, "rgt" = CASE WHEN "rgt" BETWEEN 52 AND 52 THEN "rgt" + 54 - 52 WHEN "rgt" BETWEEN 53 AND 54 THEN "rgt" + 52 - 53 ELSE "rgt" END, "parent_id" = CASE WHEN id = 27 THEN 26 ELSE "parent_id" END WHERE "marks"."markable_id" = 1 AND "marks"."markable_type" = 'Video'
  Mark Load (0.2ms)  SELECT "lft", "rgt", "parent_id" FROM "marks" WHERE "marks"."id" = 26 LIMIT 1
  Mark Load (0.1ms)  SELECT "lft", "rgt", "parent_id" FROM "marks" WHERE "marks"."id" = 27 LIMIT 1
  SQL (1.0ms)  SELECT COUNT(*) FROM "marks" WHERE "marks"."markable_id" = 1 AND "marks"."markable_type" = 'Video' AND ("marks"."lft" <= 52 AND "marks"."rgt" >= 53) AND ("marks".id != 27)
</blockquote>

<strong>TypeError: nil can't be coerced into Fixnum</strong>
    from /home/slava/.rvm/gems/ruby-1.9.2-p136/gems/nested_set-1.6.3/lib/nested_set/depth.rb:24:in `-'
    from /home/slava/.rvm/gems/ruby-1.9.2-p136/gems/nested_set-1.6.3/lib/nested_set/depth.rb:24:in`update_depth'
    from /home/slava/.rvm/gems/ruby-1.9.2-p136/gems/nested_set-1.6.3/lib/nested_set/base.rb:636:in `block in move_to'
    from /home/slava/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:413:in`_run_move_callbacks'
    from /home/slava/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:93:in `run_callbacks'
    from /home/slava/.rvm/gems/ruby-1.9.2-p136/gems/nested_set-1.6.3/lib/nested_set/base.rb:573:in`move_to'
    from /home/slava/.rvm/gems/ruby-1.9.2-p136/gems/nested_set-1.6.3/lib/nested_set/base.rb:465:in `move_to_child_of'
    from /home/slava/.rvm/gems/ruby-1.9.2-p136/gems/nested_set-1.6.3/lib/nested_set/base.rb:521:in`move_to_new_parent'
    from /home/slava/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:450:in `_run_save_
...
</code>

**Comment by skyeagle** [comment]
nested_set supposes that child will be created as:

```
child = Category.create(...)
child.move_to_child_of(Category.find(..))
```

**Comment by bitcoiners** [comment]
Ok. tried that but getting same result:

<pre>
ruby-1.9.2-p136 :029 > <strong>mark = Mark.find 5</strong>
  Mark Load (0.5ms)  SELECT "marks".* FROM "marks" WHERE "marks"."id" = 5 LIMIT 1
#<Mark:0xb764f34> {
                 :id => 5,
               :type => "Mark",
      :markable_type => "Video",
            :user_id => 1,
    :context_user_id => 1,
         :context_id => 2,
        :markable_id => 1,
          <strong>:parent_id => nil,</strong>
                :lft => 9,
                :rgt => 10,
              :depth => nil,
               :html => nil,
              :title => "label",
               :body => "",
         :created_at => Wed, 26 Jan 2011 03:22:17 UTC +00:00,
         :updated_at => Wed, 26 Jan 2011 03:22:17 UTC +00:00
}
ruby-1.9.2-p136 :030 > <strong>mark2 = Mark.find 6</strong>
  Mark Load (0.5ms)  SELECT "marks".* FROM "marks" WHERE "marks"."id" = 6 LIMIT 1
#<Mark:0xb759be8> {
                 :id => 6,
               :type => "Mark",
      :markable_type => "Video",
            :user_id => 1,
    :context_user_id => 1,
         :context_id => 2,
        :markable_id => 1,
          <strong>:parent_id => nil,</strong>
                :lft => 11,
                :rgt => 12,
              :depth => nil,
               :html => nil,
              :title => "label",
               :body => "",
         :created_at => Wed, 26 Jan 2011 03:32:20 UTC +00:00,
         :updated_at => Wed, 26 Jan 2011 03:32:20 UTC +00:00
}
ruby-1.9.2-p136 :031 > <strong>mark2.move_to_child_of mark</strong>
  Mark Load (0.3ms)  SELECT "lft", "rgt", "parent_id" FROM "marks" WHERE "marks"."id" = 5 LIMIT 1
  Mark Load (0.2ms)  SELECT "lft", "rgt", "parent_id" FROM "marks" WHERE "marks"."id" = 6 LIMIT 1
  AREL (0.5ms)  UPDATE "marks" SET "lft" = CASE WHEN "lft" BETWEEN 10 AND 10 THEN "lft" + 12 - 10 WHEN "lft" BETWEEN 11 AND 12 THEN "lft" + 10 - 11 ELSE "lft" END, "rgt" = CASE WHEN "rgt" BETWEEN 10 AND 10 THEN "rgt" + 12 - 10 WHEN "rgt" BETWEEN 11 AND 12 THEN "rgt" + 10 - 11 ELSE "rgt" END, "parent_id" = CASE WHEN id = 6 THEN 5 ELSE "parent_id" END WHERE "marks"."markable_id" = 1 AND "marks"."markable_type" = 'Video'
  Mark Load (0.3ms)  SELECT "lft", "rgt", "parent_id" FROM "marks" WHERE "marks"."id" = 5 LIMIT 1
  Mark Load (0.1ms)  SELECT "lft", "rgt", "parent_id" FROM "marks" WHERE "marks"."id" = 6 LIMIT 1
  SQL (0.2ms)  SELECT COUNT(*) FROM "marks" WHERE "marks"."markable_id" = 1 AND "marks"."markable_type" = 'Video' AND ("marks"."lft" <= 10 AND "marks"."rgt" >= 11) AND ("marks".id != 6)
<strong>TypeError: nil can't be coerced into Fixnum</strong>

from /home/slava/.rvm/gems/ruby-1.9.2-p136/gems/nested_set-1.6.3/lib/nested_set/depth.rb:24:in `-'
    from /home/slava/.rvm/gems/ruby-1.9.2-p136/gems/nested_set-1.6.3/lib/nested_set/depth.rb:24:in `update_depth'
    from /home/slava/.rvm/gems/ruby-1.9.2-p136/gems/nested_set-1.6.3/lib/nested_set/base.rb:636:in `block in move_to'
    from /home/slava/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:413:in `_run_move_callbacks'
    from /home/slava/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:93:in `run_callbacks'
    from /home/slava/.rvm/gems/ruby-1.9.2-p136/gems/nested_set-1.6.3/lib/nested_set/base.rb:573:in `move_to'
    from /home/slava/.rvm/gems/ruby-1.9.2-p136/gems/nested_set-1.6.3/lib/nested_set/base.rb:465:in `move_to_child_of'
    from (irb):31

</pre>

**Comment by skyeagle** [comment]
Ok. I see. I think it corresponds to the issue #13. Try to delete depth column or add default value to it.

**Comment by bitcoiners** [comment]
yes. deleting depth column fixed it.
setting depth to    :default => 0 
did not fix.

**Comment by skyeagle** [comment]
Did you update the exist records after you had added default value?

**Comment by bitcoiners** [comment]
yes. I ran rake db:migrate:reset and reloaded seeds

**Comment by bitcoiners** [comment]
sorry. never mind. it seems to be working with  depth :default => 0
