### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by bcoughlan** [skyeagle/nested_set#22]
Sorry if this is in the wrong place, but is there ANYWHERE I can find examples of creating sample data in seeds.rb, general usage etc?

**Comment by skyeagle** [comment]
Take a look on this [example](https://github.com/skyeagle/nested_set/issues/closed#issue/14/comment/708556)
Could you write a wiki page about it, please? It would be great!

**Comment by bcoughlan** [comment]
I'll definitely put up examples and things as I get them working.
