### ISSUE TITLE
"undefined method `level' when deployed to Heroku works locally

### ISSUE THREAD

**Issue by andkjaer** [skyeagle/nested_set#25]
ShopCategoriesController# (ActionView::Template::Error) "undefined method `level' for #Array:0x2baa5f348250"

/app/app/views/shop_categories/_form.html.erb:16:in `_app_views_shop_categories__form_html_erb___1656003407_24005371460680_1158750'
/app/.bundle/gems/ruby/1.8/gems/nested_set-1.5.4/lib/nested_set/helper.rb:38:in`nested_set_options' /app/.bundle/gems/ruby/1.8/gems/activerecord-3.0.5/lib/active_record/relation.rb:13:in `map' /app/.bundle/gems/ruby/1.8/gems/activerecord-3.0.5/lib/active_record/relation.rb:13:in`__send__' /app/.bundle/gems/ruby/1.8/gems/activerecord-3.0.5/lib/active_record/relation.rb:13:in `map' /app/.bundle/gems/ruby/1.8/gems/nested_set-1.5.4/lib/nested_set/helper.rb:30:in`nested_set_options' /app/.bundle/gems/ruby/1.8/gems/nested_set-1.5.4/lib/nested_set/helper.rb:28:in `each' /app/.bundle/gems/ruby/1.8/gems/nested_set-1.5.4/lib/nested_set/helper.rb:28:in`nested_set_options'

**Comment by skyeagle** [comment]
Could you provide a few lines of your code here, please.

**Comment by andkjaer** [comment]
Yes off course sorry.

In my form:
 <%= f.label "Category" %>
    <%= f.select :parent_id, nested_set_options(ShopCategory, @shop_category) {|i| "#{'-' \* i.level} #{i.name}" }, :include_blank => true %>

It works until I create my first category.

**Comment by skyeagle** [comment]
Current version of gem is 1.6.4 You are using 1.5.4. Try to update it.

```
/app/.bundle/gems/ruby/1.8/gems/nested_set-1.5.4/lib/nested_set/helper.rb:28:innested_set_options
```

**Comment by andkjaer** [comment]
I know, I started with the latest version but when it failed, i tried a version i know have worked before.

**Comment by skyeagle** [comment]
You should switch to 1.6.4 and provide backtrace for it.

**Comment by andkjaer** [comment]
Ok I will do that wright away. Just a quick note, if I remove
i.level and i.name it works.

**Comment by skyeagle** [comment]
Take a [look](https://github.com/skyeagle/nested_set/blob/master/lib/nested_set/helper.rb). There is the other usage of that helper(version 1.6.4):

```
    #   <%= f.select :parent_id, nested_set_options(Category, @category) {|i, level|
    #       "#{'–' * level} #{i.name}"
    #     }) %>
```

Two variables are passed into the block.

**Comment by andkjaer** [comment]
Thank you, that fixed it :O)

**Comment by skyeagle** [comment]
You are welcome
