### ISSUE TITLE
:depth collumn not updated/filled in any situation, it is always null

### ISSUE THREAD

**Issue by daliborfilus** [skyeagle/nested_set#29]
Hi, I have depth collumn (integer) in my table, but it is never updated, or filled...
When I create new record, it is null.
When I move record as someones children, it is still null...

I don't know if the support for it is dropped (if it is, it should be mentioned in the doc)...

I'm not using it, but ... maybe someone reiles on it :)

Schema dump:

``` ruby
  create_table "regions", :force => true do |t|
    t.string   "name",                      :null => false
    t.string   "slug"
    t.string   "code",       :limit => 128
    t.string   "helpcode",   :limit => 128
    t.integer  "lft"
    t.integer  "rgt"
    t.integer  "parent_id"
    t.integer  "depth"
    t.datetime "created_at"
    t.datetime "updated_at"
  end
```

Using rails 3.1 rc1,
nested_set gem 1.6.5
mysql2 0.3.2

Anyway, thanks for all your work, I use this gem in my 4 projects :)

Regards, NoICE

**Comment by skyeagle** [comment]
Yep, I see there is the bug. It depends on the depth column default value as NULL opposite 0. I will correct it soon. Thanks for the mention.
