### ISSUE TITLE
Ordering elements

### ISSUE THREAD

**Issue by lphm** [skyeagle/nested_set#30]
Hello,

I currently use <code>acts_as_tree</code> in my models with this line :

<code>acts_as_tree :order => "weight", :counter_cache => true
</code>

I want to switch on <code>nested_set</code> gem but how to keep weight order mechanism in my models ?

Thanks for your help.

**Comment by skyeagle** [comment]
Hi!

Keep the weight and order your items when you are rendering the list. There are [a few](https://github.com/skyeagle/nested_set/blob/master/lib/nested_set/helper.rb) helpers to help you. 
You would be better take a look on the [ancestry](https://github.com/stefankroes/ancestry) gem if you have already had manual ordering, I mean weight.
