### ISSUE TITLE
`nested_set_options` helper won't accept ActiveRecord::Relation

### ISSUE THREAD

**Issue by iamvery** [skyeagle/nested_set#34]
This very well be me over/under thinking the problem, but I ran into an issue today where trying to render a set of records from a `Relation`. That is, maybe I would like to run it against a subset of the `root` nodes:

```
# nested_set_options(Category.new.roots) # edited to fix scope naming conflict...
nested_set_options(Category.recent.roots) # block intentionally left off
```

The problem is that it takes anything that isn't a `Class` or an `Array` and wraps it in an array before iterating over it. It then tries calling `self_and_descendants` on the `ActiveRecord::Relation` itself instead of each of its results.

I didn't want to take it upon myself quite yet to "fix" this because I'm not entirely sure it is unintentional. Is there a reason I shouldn't be able to pass in a relation to this helper? Could it be as simple as:

```
when class_or_items.is_a?(Array) or class_or_items.is_a?(ActiveRecord::Relation)
```

Anyway, hope I haven't completely missed the point :P. Btw, I do realize I can tag on a `.all` to my `Relation` to get the results in an array. That is the "fix" I'm using currently.

**Comment by skyeagle** [comment]
`Category.new.roots` its a wrong code, you should use it like:

``` ruby
nested_set_options(Category)
```

If you would like to use relation just call `to_a` on it and keep in mind that the relation must return top level nodes only.

``` ruby
nested_set_options(Category.find(..).self_and_siblings.to_a)
```

It also takes an instance and wraps it to an array that you could understand on the example below:

``` ruby
nested_set_options(current_user.root_folder)
```

Anyway, It would be great if you'll add functionality for relations with tests and make a pull request.

**Comment by iamvery** [comment]
Hah, I wrote that in a hurry and just made up `Category.new.roots`. Yeah you'd have a naming issue with a scope named `new`. Consider this, as I understand it the `root` scope ensures that only top level nodes are returned:

```
# in Category model that acts_as_nested_set
scope :today, where(:created_at => Date.today)

# in some view
nested_set_options(Category.today.roots) # lots of code intentionally left off...
```

Thanks for the `to_a` hint, thats probably better than `all`. I was having some trouble traversing `ActiveRecord`'s documentation and missed that method.

Seriously, thank you for getting back to me. If I get some time today, I'll play around with a patch for this. I really think at best, it'd be a good idea for it not to crap out if it hits a relation since the practice of using scopes has become such commonplace. Blessings!
