### ISSUE TITLE
left_sibling and right_sibling returning nil

### ISSUE THREAD

**Issue by jcm** [skyeagle/nested_set#38]
Hi,

When using left_sibling on the most left item of a sibling, it returns nil; I would have expected to return itself.
Idem with using right_sibling with the most right item of a sibling.
It would be simple to change it ( <= instead of < in the test).
Is that the expected behaviour or not ?
Thanks,

**Comment by skyeagle** [comment]
I suppose, condition with comparison on nil much simpler. We can just write:

``` ruby
if lft_sibling = left_sibling
  somithing with `lft_sibling` goes here
```

instead of

``` ruby
if lft_sibling = left_sibling and lft_sibling != self
  somithing with `lft_sibling` goes here
```

Then, it's normal behaviour.
