### ISSUE TITLE
:counter_cache?

### ISSUE THREAD

**Issue by KevinTriplett** [skyeagle/nested_set#47]
Is there a reason against adding an option to specify :counter_cache on the parent association? Like:

```
          belongs_to :parent, :class_name => self.base_class.to_s,
            :foreign_key => parent_column_name,
            :counter_cache => options[:children_counter_cache]
```

There must be a reason since none of the nested_sets seem to have this option and no one has asked for it in any of the issues. In my app, I get a crap ton of SQL COUNT(*) queries being executed. They hit the cache, which is okay, but might be nice to avoid executing the SQL in the first place.

I'll be happy to fork and add this feature, if no objections. Thanks, this is an (awesome_)nested_set!

**Comment by KevinTriplett** [comment]
Okay, I see one problem: with optimistic locking `lock_version` attribute on the model, destroying a parent causes a stale object exception since we're bypassing the built-in AR destroy code. Might be trickier than I thought?

**Comment by skyeagle** [comment]
Take a look on [this](https://github.com/skyeagle/nested_set/blob/master/lib/nested_set/descendants.rb#L7) method for the first case. Could you provide an example or fallen spec with optimistic locking, please?

**Comment by KevinTriplett** [comment]
Thanks for this -- but the count SQL is coming from Rails so I'll have to find in my code where it gets triggered (like maybe a call to `empty?` and see if I can use `has_descendants?` instead, or whatever). BTW, this `descedants_count` is one of the (awesome) features of nested_set, but a children_count cache_counter would be useful for getting only the number of children.

I'll see if I can recreate the failure I'm getting after adding a children_count counter_cache (if I still need it after your hint).
