### ISSUE TITLE
Именование render_tree хелпера

### ISSUE THREAD

**Issue by the-teacher** [skyeagle/nested_set#54]
Привет, Антон!

Мне требуется твоя консультация.
Я делаю хелпер для отрисовки деревьев. Он работает на клиентсокй стороне - а потому очень быстрый. В разы быстрее чем отрисовка на сервере.

https://github.com/the-teacher/the_sortable_tree/blob/master/app/assets/javascripts/tree/initializer.coffee

  # Benchmark:
  #3 level deep
  #25 nodes per level
  #16275 nodes in tree
  # Server rendering: 4906.3ms
  # Client rendering: 3056ms
  # Total perfomance: 16000/7 = 2200 elements per second

У меня есть серверный хелпер, который по стечению обстоятельств называется render_tree

https://github.com/the-teacher/the_sortable_tree/blob/master/app/helpers/the_sortable_tree_helper.rb#L25

Как по твоему мнению, стоит ли мне как то переименовать хелпер и, возможно, ты подскажешь вариант?

Обращаюсь к тебе, потому что пока хелпер с таким именем нашел только у тебя.

Заранее спасибо!

**Comment by flowerett** [comment]
Привет! 
Советовать дело неблагодарное :)
Если хочешь оригинально, то grow_tree
Или просто coffee_tree
Больше ничего на ум не пришло.

Но я бы оставил без изменений, главное, чтобы работало хорошо.

**Comment by the-teacher** [comment]
ок, оставлю так, кому надо - форкнет и поправит под себя.
Спасибо!

**Comment by skyeagle** [comment]
Sorry guys. Нотификация на гитхабе подвела, только увидел. Если все на этапе разработки и данный гем в зависимостях, то лучше назвать по-другому.

**Comment by the-teacher** [comment]
ок, спасибо. учту.
